apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-app
  template:
    metadata:
      labels:
        app: school-app
    spec:
      containers:
        - name: app
          image: gcr.io/applied-mystery-384107/spring
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/school-app
            - name: JWT_AUDIENCES
              valueFrom:
                secretKeyRef:
                  name: jwt-audiences
                  key: audiences
                  optional: false
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: school-app
spec:
  selector:
    app: school-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer